<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__)
    // ->exclude([
    //     'autogenerated_content',
    //     'tests/fixtures',
    // ])
    // ->notPath([
    //     'dump.php',
    //     'src/exception_file.php',
    // ])
;

return (new PhpCsFixer\Config())
    ->setRules([
        '@PSR12' => true,
        // 'strict_param' => true,
        'array_syntax' => ['syntax' => 'short'],
        '@PHP80Migration' => true,
        '@PER-CS' => true,
        // '@PHP82Migration' => true,
    ])
    ->setFinder($finder)
;
